import type { Stock } from "../types";

export const stockData: Stock[] = [
  {
    stock_name: "Morgan PLC",
    stock_symbol: "MOR",
    base_price: 8185.57,
    wishlist: false,
  },
  {
    stock_name: "Estes-Parker",
    stock_symbol: "EST",
    base_price: 5836.15,
    wishlist: false,
  },
  {
    stock_name: "Peterson Ltd",
    stock_symbol: "PET",
    base_price: 8993.01,
    wishlist: false,
  },
  {
    stock_name: "Miller-Whitney",
    stock_symbol: "MIL",
    base_price: 2393.88,
    wishlist: false,
  },
  {
    stock_name: "Williams-Castillo",
    stock_symbol: "WIL",
    base_price: 4330.14,
    wishlist: false,
  },
  {
    stock_name: "Mccormick-Hall",
    stock_symbol: "MCC",
    base_price: 9340.85,
    wishlist: false,
  },
  {
    stock_name: "Jones Ltd",
    stock_symbol: "JON",
    base_price: 5670.47,
    wishlist: false,
  },
  {
    stock_name: "Johnston Ltd",
    stock_symbol: "JOH",
    base_price: 9353.92,
    wishlist: false,
  },
  {
    stock_name: "Adams Group",
    stock_symbol: "ADA",
    base_price: 5835.63,
    wishlist: false,
  },
  {
    stock_name: "Smith, Gomez and Torres",
    stock_symbol: "SMI",
    base_price: 5921.13,
    wishlist: false,
  },
  {
    stock_name: "Wilson-Gilbert",
    stock_symbol: "WIL",
    base_price: 9780.58,
    wishlist: false,
  },
  {
    stock_name: "Leon-Pierce",
    stock_symbol: "LEO",
    base_price: 1572.05,
    wishlist: false,
  },
  {
    stock_name: "Wagner, Hahn and Floyd",
    stock_symbol: "WAG",
    base_price: 7641.95,
    wishlist: false,
  },
  {
    stock_name: "Mckenzie Group",
    stock_symbol: "MCK",
    base_price: 6967.77,
    wishlist: false,
  },
  {
    stock_name: "Jones-Caldwell",
    stock_symbol: "JON",
    base_price: 6968.38,
    wishlist: false,
  },
  {
    stock_name: "Perez-Ward",
    stock_symbol: "PER",
    base_price: 8544.11,
    wishlist: false,
  },
  {
    stock_name: "Cantu, Brown and James",
    stock_symbol: "CAN",
    base_price: 6804.68,
    wishlist: false,
  },
  {
    stock_name: "Hampton-Johnston",
    stock_symbol: "HAM",
    base_price: 6658.31,
    wishlist: false,
  },
  {
    stock_name: "Wright, Stevens and Roberts",
    stock_symbol: "WRI",
    base_price: 5465.38,
    wishlist: false,
  },
  {
    stock_name: "Olson PLC",
    stock_symbol: "OLS",
    base_price: 2532.86,
    wishlist: false,
  },
  {
    stock_name: "Thomas, Reed and Davis",
    stock_symbol: "THO",
    base_price: 6843.02,
    wishlist: false,
  },
  {
    stock_name: "Hunter, Washington and Higgins",
    stock_symbol: "HUN",
    base_price: 7374.93,
    wishlist: false,
  },
  {
    stock_name: "Mahoney Ltd",
    stock_symbol: "MAH",
    base_price: 1598.21,
    wishlist: false,
  },
  {
    stock_name: "Wilson-Smith",
    stock_symbol: "WIL",
    base_price: 4998.91,
    wishlist: false,
  },
  {
    stock_name: "Fisher PLC",
    stock_symbol: "FIS",
    base_price: 6795.34,
    wishlist: false,
  },
  {
    stock_name: "Barrera-Proctor",
    stock_symbol: "BAR",
    base_price: 6883.48,
    wishlist: false,
  },
  {
    stock_name: "Morales LLC",
    stock_symbol: "MOR",
    base_price: 9002.92,
    wishlist: false,
  },
  {
    stock_name: "Velasquez-Gallagher",
    stock_symbol: "VEL",
    base_price: 4499.06,
    wishlist: false,
  },
  {
    stock_name: "Kelly Inc",
    stock_symbol: "KEL",
    base_price: 6374.03,
    wishlist: false,
  },
  {
    stock_name: "Smith Ltd",
    stock_symbol: "SMI",
    base_price: 5581.7,
    wishlist: false,
  },
  {
    stock_name: "Garner Ltd",
    stock_symbol: "GAR",
    base_price: 792.02,
    wishlist: false,
  },
  {
    stock_name: "Berry, Davis and Lawson",
    stock_symbol: "BER",
    base_price: 7353.99,
    wishlist: false,
  },
  {
    stock_name: "May, Davis and Oconnor",
    stock_symbol: "MAY",
    base_price: 1767.37,
    wishlist: false,
  },
  {
    stock_name: "Weber, Davis and Watson",
    stock_symbol: "WEB",
    base_price: 8630.4,
    wishlist: false,
  },
  {
    stock_name: "Fox, Villanueva and Conley",
    stock_symbol: "FOX",
    base_price: 3741.41,
    wishlist: false,
  },
  {
    stock_name: "Ferrell-Lee",
    stock_symbol: "FER",
    base_price: 7541.44,
    wishlist: false,
  },
  {
    stock_name: "Stein LLC",
    stock_symbol: "STE",
    base_price: 9786.77,
    wishlist: false,
  },
  {
    stock_name: "Jackson-Sweeney",
    stock_symbol: "JAC",
    base_price: 2028.19,
    wishlist: false,
  },
  {
    stock_name: "Banks-Proctor",
    stock_symbol: "BAN",
    base_price: 5586.78,
    wishlist: false,
  },
  {
    stock_name: "Reed, White and Donovan",
    stock_symbol: "REE",
    base_price: 6074.71,
    wishlist: false,
  },
  {
    stock_name: "Colon-Weaver",
    stock_symbol: "COL",
    base_price: 8804.48,
    wishlist: false,
  },
  {
    stock_name: "Stone-Martinez",
    stock_symbol: "STO",
    base_price: 1234.66,
    wishlist: false,
  },
  {
    stock_name: "Brady, Smith and Anderson",
    stock_symbol: "BRA",
    base_price: 4732.48,
    wishlist: false,
  },
  {
    stock_name: "Francis, Price and Williams",
    stock_symbol: "FRA",
    base_price: 7919.09,
    wishlist: false,
  },
  {
    stock_name: "Richards-Atkinson",
    stock_symbol: "RIC",
    base_price: 9074.13,
    wishlist: false,
  },
  {
    stock_name: "Anderson, Garcia and Sherman",
    stock_symbol: "AND",
    base_price: 9473.26,
    wishlist: false,
  },
  {
    stock_name: "Jensen, Smith and Robinson",
    stock_symbol: "JEN",
    base_price: 4469.75,
    wishlist: false,
  },
  {
    stock_name: "Scott Ltd",
    stock_symbol: "SCO",
    base_price: 5273.75,
    wishlist: false,
  },
  {
    stock_name: "Ramirez-Anderson",
    stock_symbol: "RAM",
    base_price: 9492.36,
    wishlist: false,
  },
  {
    stock_name: "West, Miller and Fernandez",
    stock_symbol: "WES",
    base_price: 7086.89,
    wishlist: false,
  },
  {
    stock_name: "Watts, Smith and Cross",
    stock_symbol: "WAT",
    base_price: 7074.97,
    wishlist: false,
  },
  {
    stock_name: "Price PLC",
    stock_symbol: "PRI",
    base_price: 8211.81,
    wishlist: false,
  },
  {
    stock_name: "Gilbert and Sons",
    stock_symbol: "GIL",
    base_price: 8026.7,
    wishlist: false,
  },
  {
    stock_name: "King, Green and Wallace",
    stock_symbol: "KIN",
    base_price: 4238.61,
    wishlist: false,
  },
  {
    stock_name: "Oconnor LLC",
    stock_symbol: "OCO",
    base_price: 2722.14,
    wishlist: false,
  },
  {
    stock_name: "Moore-Tucker",
    stock_symbol: "MOO",
    base_price: 4047.32,
    wishlist: false,
  },
  {
    stock_name: "Young-Brown",
    stock_symbol: "YOU",
    base_price: 7002.67,
    wishlist: false,
  },
  {
    stock_name: "Cummings and Sons",
    stock_symbol: "CUM",
    base_price: 6590.83,
    wishlist: false,
  },
  {
    stock_name: "Clarke, Johnson and Roberts",
    stock_symbol: "CLA",
    base_price: 1641.92,
    wishlist: false,
  },
  {
    stock_name: "Ford-West",
    stock_symbol: "FOR",
    base_price: 6782.63,
    wishlist: false,
  },
  {
    stock_name: "Henderson-Holden",
    stock_symbol: "HEN",
    base_price: 7179.54,
    wishlist: false,
  },
  {
    stock_name: "Perry, Taylor and Gonzalez",
    stock_symbol: "PER",
    base_price: 3594.82,
    wishlist: false,
  },
  {
    stock_name: "Boyd, Barker and Miller",
    stock_symbol: "BOY",
    base_price: 570.06,
    wishlist: false,
  },
  {
    stock_name: "Taylor-Fernandez",
    stock_symbol: "TAY",
    base_price: 8621.74,
    wishlist: false,
  },
  {
    stock_name: "Clark-Warner",
    stock_symbol: "CLA",
    base_price: 4362.6,
    wishlist: false,
  },
  {
    stock_name: "Ortega-Baldwin",
    stock_symbol: "ORT",
    base_price: 5418.25,
    wishlist: false,
  },
  {
    stock_name: "Williams, Chavez and Gamble",
    stock_symbol: "WIL",
    base_price: 7927.38,
    wishlist: false,
  },
  {
    stock_name: "Sanders, Gibbs and Burgess",
    stock_symbol: "SAN",
    base_price: 3514.32,
    wishlist: false,
  },
  {
    stock_name: "Shea, Garcia and Valdez",
    stock_symbol: "SHE",
    base_price: 8861.25,
    wishlist: false,
  },
  {
    stock_name: "Barton PLC",
    stock_symbol: "BAR",
    base_price: 9596.16,
    wishlist: false,
  },
  {
    stock_name: "Robertson Ltd",
    stock_symbol: "ROB",
    base_price: 1661.72,
    wishlist: false,
  },
  {
    stock_name: "Phillips LLC",
    stock_symbol: "PHI",
    base_price: 8419.23,
    wishlist: false,
  },
  {
    stock_name: "Rodriguez-Snyder",
    stock_symbol: "ROD",
    base_price: 4455.6,
    wishlist: false,
  },
  {
    stock_name: "Jennings-Howard",
    stock_symbol: "JEN",
    base_price: 1192.95,
    wishlist: false,
  },
  {
    stock_name: "Nelson-Baker",
    stock_symbol: "NEL",
    base_price: 775.02,
    wishlist: false,
  },
  {
    stock_name: "Jones-Salazar",
    stock_symbol: "JON",
    base_price: 5957.28,
    wishlist: false,
  },
  {
    stock_name: "Saunders, Simpson and Evans",
    stock_symbol: "SAU",
    base_price: 920.63,
    wishlist: false,
  },
  {
    stock_name: "Bishop-Diaz",
    stock_symbol: "BIS",
    base_price: 2762.7,
    wishlist: false,
  },
  {
    stock_name: "Gutierrez Ltd",
    stock_symbol: "GUT",
    base_price: 8211.49,
    wishlist: false,
  },
  {
    stock_name: "Mayo, Smith and Sullivan",
    stock_symbol: "MAY",
    base_price: 2361.29,
    wishlist: false,
  },
  {
    stock_name: "Simon, Rivera and Moore",
    stock_symbol: "SIM",
    base_price: 9993.49,
    wishlist: false,
  },
  {
    stock_name: "Murray Inc",
    stock_symbol: "MUR",
    base_price: 6606.97,
    wishlist: false,
  },
  {
    stock_name: "White Ltd",
    stock_symbol: "WHI",
    base_price: 6696.72,
    wishlist: false,
  },
  {
    stock_name: "Lee Group",
    stock_symbol: "LEE",
    base_price: 998.2,
    wishlist: false,
  },
  {
    stock_name: "Brown-Foster",
    stock_symbol: "BRO",
    base_price: 3840.25,
    wishlist: false,
  },
  {
    stock_name: "Rivas-Jones",
    stock_symbol: "RIV",
    base_price: 8825.69,
    wishlist: false,
  },
  {
    stock_name: "Pierce, Middleton and Ortega",
    stock_symbol: "PIE",
    base_price: 8962.89,
    wishlist: false,
  },
  {
    stock_name: "Mccormick-Frost",
    stock_symbol: "MCC",
    base_price: 1066.57,
    wishlist: false,
  },
  {
    stock_name: "Peterson-Barnett",
    stock_symbol: "PET",
    base_price: 7172.11,
    wishlist: false,
  },
  {
    stock_name: "Bowen-Rocha",
    stock_symbol: "BOW",
    base_price: 8489.03,
    wishlist: false,
  },
  {
    stock_name: "Mcmahon-Terry",
    stock_symbol: "MCM",
    base_price: 6006.95,
    wishlist: false,
  },
  {
    stock_name: "Huffman Ltd",
    stock_symbol: "HUF",
    base_price: 437.26,
    wishlist: false,
  },
  {
    stock_name: "Butler-Morgan",
    stock_symbol: "BUT",
    base_price: 8751.85,
    wishlist: false,
  },
  {
    stock_name: "Taylor-Lloyd",
    stock_symbol: "TAY",
    base_price: 4665.27,
    wishlist: false,
  },
  {
    stock_name: "Bartlett and Sons",
    stock_symbol: "BAR",
    base_price: 9897.12,
    wishlist: false,
  },
  {
    stock_name: "Reid, James and Sanchez",
    stock_symbol: "REI",
    base_price: 1711.45,
    wishlist: false,
  },
  {
    stock_name: "Nash, Chen and Diaz",
    stock_symbol: "NAS",
    base_price: 5685.18,
    wishlist: false,
  },
  {
    stock_name: "Gould Ltd",
    stock_symbol: "GOU",
    base_price: 568.98,
    wishlist: false,
  },
  {
    stock_name: "Espinoza, Wilcox and Crawford",
    stock_symbol: "ESP",
    base_price: 3260.18,
    wishlist: false,
  },
  {
    stock_name: "Townsend Ltd",
    stock_symbol: "TOW",
    base_price: 1598.97,
    wishlist: false,
  }
]
